name: CI

on:
  workflow_dispatch:
  schedule:
    - cron: 0 0 * * *
  pull_request:
  push:

jobs:
  build:

    runs-on: macos-latest

    steps:
    - uses: actions/checkout@v2-beta
    - name: Select Xcode version
      run: sudo xcode-select -s '/Applications/Xcode_11.2.app/Contents/Developer'
    - name: CocoaPods
      run: pod install
    - name: Show Xcode version
      run: xcodebuild -version