name: CI

on:
  workflow_dispatch:
  schedule:
    - cron: 0 0 * * *
  pull_request:

jobs:
  build:
    runs-on: macos-latest
    timeout-minutes: 60
    strategy:
    fail-fast: false
    matrix:
      target: ["iPhone 12 Pro Max", "iPhone 11 Pro"]
    steps:
    - uses: actions/checkout@v2-beta
    - name: Select Xcode version
      run: sudo xcode-select -s '/Applications/Xcode_11.2.app/Contents/Developer'
    # CocoaPodsを使うようになったらここのコメントアウトを外す
    # - name: CocoaPods
    #  run: pod install
    - name: Show Xcode version
      run: xcodebuild -version
    - name: Build with xcode
      run: xcodebuild -sdk iphonesimulator -configuration Debug -destination 'platform=iOS Simulator,name=${{ matrix.target }}' clean test | xcpretty